
export const resumes = [
  {
    id: "1",
    companyName: "Pfizer",
    jobTitle: "Data Analyst",
    imagePath: "",
    resumePath: "",
    feedback: {
      overallScore: 83,
      ATS: { score: 86, tips: [] },
      toneAndStyle: { score: 82, tips: [] },
      content: { score: 84, tips: [] },
      structure: { score: 80, tips: [] },
      skills: { score: 85, tips: [] },
    },
  },
  {
    id: "2",
    companyName: "John Deere",
    jobTitle: "IT Project Manager",
    imagePath: "",
    resumePath: "",
    feedback: {
      overallScore: 88,
      ATS: { score: 91, tips: [] },
      toneAndStyle: { score: 89, tips: [] },
      content: { score: 90, tips: [] },
      structure: { score: 87, tips: [] },
      skills: { score: 86, tips: [] },
    },
  },
  {
    id: "3",
    companyName: "UnitedHealth Group",
    jobTitle: "Business Intelligence Specialist",
    imagePath: "",
    resumePath: "",
    feedback: {
      overallScore: 90,
      ATS: { score: 93, tips: [] },
      toneAndStyle: { score: 91, tips: [] },
      content: { score: 92, tips: [] },
      structure: { score: 89, tips: [] },
      skills: { score: 88, tips: [] },
    },
  },
  {
    id: "4",
    companyName: "Verizon",
    jobTitle: "Cybersecurity Analyst",
    imagePath: "",
    resumePath: "",
    feedback: {
      overallScore: 85,
      ATS: { score: 87, tips: [] },
      toneAndStyle: { score: 83, tips: [] },
      content: { score: 84, tips: [] },
      structure: { score: 82, tips: [] },
      skills: { score: 85, tips: [] },
    },
  },
  {
    id: "5",
    companyName: "The Coca-Cola Company",
    jobTitle: "Digital Marketing Strategist",
    imagePath: "",
    resumePath: "",
    feedback: {
      overallScore: 86,
      ATS: { score: 89, tips: [] },
      toneAndStyle: { score: 87, tips: [] },
      content: { score: 88, tips: [] },
      structure: { score: 84, tips: [] },
      skills: { score: 85, tips: [] },
    },
  },
]